name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      TIMEZONE:
        description: "Podaj strefę czasową (CEST lub CET)"
        required: true
        type: string
        #default: "CEST"
      DATE1:
        description: "Podaj pierwszą datę (format: DD.MM.YYYY)"
        required: true
        type: string
      DATE2:
        description: "Podaj drugą datę (format: DD.MM.YYYY)"
        required: true
        type: string
      TIME1:
        description: "Podaj pierwszy czas (format: HH:MM)"
        required: true
        type: string
      TIME2:
        description: "Podaj drugi czas (format: HH:MM)"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ustawianie zmiennych środowiskowych
        run: |
          echo "TIMEZONE=${{ inputs.TIMEZONE }}" >> $GITHUB_ENV
          echo "DATE1=${{ inputs.DATE1 }}" >> $GITHUB_ENV
          echo "DATE2=${{ inputs.DATE2 }}" >> $GITHUB_ENV
          echo "TIME1=${{ inputs.TIME1 }}" >> $GITHUB_ENV
          echo "TIME2=${{ inputs.TIME2 }}" >> $GITHUB_ENV

      - name: Wypisanie zmiennych (DEBUG)
        run: |
          echo "TIMEZONE=$TIMEZONE"
          echo "DATE1=$DATE1"
          echo "DATE2=$DATE2"
          echo "TIME1=$TIME1"
          echo "TIME2=$TIME2"

      - name: Tworzenie pliku Time_zone_generation.py
        run: |
          cat <<EOL > Time_zone_generation.py
          import sys

          def main():
              timezone = sys.argv[1]
              date1 = sys.argv[2]
              date2 = sys.argv[3]
              time1 = sys.argv[4]
              time2 = sys.argv[5]

              if timezone not in ["CEST", "CET"]:
                  print("Niepoprawna wartość strefy czasowej!")
                  sys.exit(1)

              print(f"Strefa czasowa: {timezone}")
              print(f"Data 1: {date1}")
              print(f"Data 2: {date2}")
              print(f"Czas 1: {time1}")
              print(f"Czas 2: {time2}")

          if __name__ == "__main__":
              main()
          EOL
      
      - name: Sprawdzenie, czy plik `Time_zone_generation.py` istnieje
        run: |
          if [ -f "Time_zone_generation.py" ]; then
            echo "✅ Plik Time_zone_generation.py istnieje."
          else
            echo "❌ Brak pliku Time_zone_generation.py! Sprawdź, czy znajduje się w repozytorium."
            exit 1
          fi

      - name: Uruchamianie skryptu i przekierowanie wyników do logów
        run: |
          python Time_zone_generation.py "$TIMEZONE" "$DATE1" "$DATE2" "$TIME1" "$TIME2" | tee output.log

      - name: Wypisanie wyników skryptu w logach GitHub Actions
        run: cat output.log