name: Build Banner with Selected Region and Timezone

on:
  workflow_dispatch:
    inputs:
      REGION:
        description: "Select the region to calculate (EMEA, AMERICA, CHINA)"
        required: true
        type: choice
        options:
          - EMEA
          - AMERICA
          - CHINA

      TIMEZONE:
        description: "Select the timezone for EMEA (CEST or CET)"
        required: true
        type: choice
        options:
          - CEST
          - CET

      DATE1:
        description: "Enter the first date (format: DD.MM.YYYY)"
        required: true
        type: string
      DATE2:
        description: "Enter the second date (format: DD.MM.YYYY)"
        required: true
        type: string
      TIME1:
        description: "Enter the first time (format: HH:MM)"
        required: true
        type: string
      TIME2:
        description: "Enter the second time (format: HH:MM)"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up the latest Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tzdata

      - name: Setting environment variables
        run: |
          echo "REGION=${{ inputs.REGION }}" >> $GITHUB_ENV
          echo "TIMEZONE=${{ inputs.TIMEZONE }}" >> $GITHUB_ENV
          echo "DATE1=${{ inputs.DATE1 }}" >> $GITHUB_ENV
          echo "DATE2=${{ inputs.DATE2 }}" >> $GITHUB_ENV
          echo "TIME1=${{ inputs.TIME1 }}" >> $GITHUB_ENV
          echo "TIME2=${{ inputs.TIME2 }}" >> $GITHUB_ENV

      - name: Checking whether the file `Time_zone_generation.py` exists
        run: |
          ls -la
          if [ -f "${{ github.workspace }}/time_zone_multi_time_for_each_time_zone/Time_zone_generation.py" ]; then
            echo "✅ The file Time_zone_generation.py was found."
          else
            echo "❌ Time_zone_generation.py file is missing! Check its location in the repository."
            exit 1
          fi

      - name: Running the script for selected region and timezone
        run: |
          python ${{ github.workspace }}/time_zone_multi_time_for_each_time_zone/Time_zone_generation.py "$REGION" "$TIMEZONE" "$DATE1" "$DATE2" "$TIME1" "$TIME2"

      - name: Cache output file
        uses: actions/cache@v4
        with:
          path: output_banner.txt
          key: output-banner-${{ github.run_id }}

      - name: Upload output file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_banner-${{ github.run_id }}
          path: output_banner.txt