name: Build Banner with Multiple Timezones

on:
  workflow_dispatch:
    inputs:
      EMEA_TIMEZONE:
        description: "Enter the time zone for EMEA (CEST or CET)"
        required: true
        type: string
      EMEA_DATE1:
        description: "Enter the first date for EMEA (format: DD.MM.YYYY)"
        required: true
        type: string
      EMEA_DATE2:
        description: "Enter the second date for EMEA (format: DD.MM.YYYY)"
        required: true
        type: string
      EMEA_TIME1:
        description: "Enter the first time for EMEA (format: HH:MM)"
        required: true
        type: string
      EMEA_TIME2:
        description: "Enter the second time for EMEA (format: HH:MM)"
        required: true
        type: string

      AMERICA_TIMEZONE:
        description: "Enter the time zone for America (e.g., EST, PST)"
        required: true
        type: string
      AMERICA_DATE1:
        description: "Enter the first date for America (format: DD.MM.YYYY)"
        required: true
        type: string
      AMERICA_DATE2:
        description: "Enter the second date for America (format: DD.MM.YYYY)"
        required: true
        type: string
      AMERICA_TIME1:
        description: "Enter the first time for America (format: HH:MM)"
        required: true
        type: string
      AMERICA_TIME2:
        description: "Enter the second time for America (format: HH:MM)"
        required: true
        type: string

      CHINA_TIMEZONE:
        description: "Enter the time zone for China (e.g., CST)"
        required: true
        type: string
      CHINA_DATE1:
        description: "Enter the first date for China (format: DD.MM.YYYY)"
        required: true
        type: string
      CHINA_DATE2:
        description: "Enter the second date for China (format: DD.MM.YYYY)"
        required: true
        type: string
      CHINA_TIME1:
        description: "Enter the first time for China (format: HH:MM)"
        required: true
        type: string
      CHINA_TIME2:
        description: "Enter the second time for China (format: HH:MM)"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up the latest Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tzdata

      - name: Setting environment variables
        run: |
          echo "EMEA_TIMEZONE=${{ inputs.EMEA_TIMEZONE }}" >> $GITHUB_ENV
          echo "EMEA_DATE1=${{ inputs.EMEA_DATE1 }}" >> $GITHUB_ENV
          echo "EMEA_DATE2=${{ inputs.EMEA_DATE2 }}" >> $GITHUB_ENV
          echo "EMEA_TIME1=${{ inputs.EMEA_TIME1 }}" >> $GITHUB_ENV
          echo "EMEA_TIME2=${{ inputs.EMEA_TIME2 }}" >> $GITHUB_ENV

          echo "AMERICA_TIMEZONE=${{ inputs.AMERICA_TIMEZONE }}" >> $GITHUB_ENV
          echo "AMERICA_DATE1=${{ inputs.AMERICA_DATE1 }}" >> $GITHUB_ENV
          echo "AMERICA_DATE2=${{ inputs.AMERICA_DATE2 }}" >> $GITHUB_ENV
          echo "AMERICA_TIME1=${{ inputs.AMERICA_TIME1 }}" >> $GITHUB_ENV
          echo "AMERICA_TIME2=${{ inputs.AMERICA_TIME2 }}" >> $GITHUB_ENV

          echo "CHINA_TIMEZONE=${{ inputs.CHINA_TIMEZONE }}" >> $GITHUB_ENV
          echo "CHINA_DATE1=${{ inputs.CHINA_DATE1 }}" >> $GITHUB_ENV
          echo "CHINA_DATE2=${{ inputs.CHINA_DATE2 }}" >> $GITHUB_ENV
          echo "CHINA_TIME1=${{ inputs.CHINA_TIME1 }}" >> $GITHUB_ENV
          echo "CHINA_TIME2=${{ inputs.CHINA_TIME2 }}" >> $GITHUB_ENV

      - name: Checking whether the file `Time_zone_generation.py` exists
        run: |
          ls -la
          if [ -f "${{ github.workspace }}/time_zone/Time_zone_generation.py" ]; then
            echo "✅ The file Time_zone_generation.py was found."
          else
            echo "❌ Time_zone_generation.py file is missing! Check its location in the repository."
            exit 1
          fi

      - name: Running the script for EMEA
        run: |
          python ${{ github.workspace }}/time_zone_multi_time_for_each_time_zone/Time_zone_generation.py "$EMEA_TIMEZONE" "$EMEA_DATE1" "$EMEA_DATE2" "$EMEA_TIME1" "$EMEA_TIME2"

      - name: Running the script for America
        run: |
          python ${{ github.workspace }}/time_zone_multi_time_for_each_time_zone/Time_zone_generation.py "$AMERICA_TIMEZONE" "$AMERICA_DATE1" "$AMERICA_DATE2" "$AMERICA_TIME1" "$AMERICA_TIME2"

      - name: Running the script for China
        run: |
          python ${{ github.workspace }}/time_zone_multi_time_for_each_time_zone/Time_zone_generation.py "$CHINA_TIMEZONE" "$CHINA_DATE1" "$CHINA_DATE2" "$CHINA_TIME1" "$CHINA_TIME2"

      - name: Cache output file
        uses: actions/cache@v4
        with:
          path: output_banner.txt
          key: output-banner-${{ github.run_id }}

      - name: Upload output file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_banner-${{ github.run_id }}
          path: output_banner.txt